version: '3'

services:
  proxy:
    image: ${TRAEFIK_IMAGE:?Set TRAEFIK_IMAGE to a verified image reference}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443" #
    restart: unless-stopped
    networks:
      - traefik-public
      - proxy-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.router_proxy.rule=Host(`localhost`)
      - traefik.http.routers.router_proxy.entrypoints=web #
      - traefik.http.routers.router_proxy.service=api@internal
      - traefik.http.routers.router_proxy.middlewares=https-redirect #
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https #
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true #
      - traefik.http.routers.router_proxy.tls=false #
      - traefik.http.routers.router_proxy.tls.certresolver=le #
      - traefik.http.services.router_proxy.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
  proxy-net:
    external: true
